import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Payam Kar',
      email: '21389629@student.uwl.ac.uk',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: true,
      isSeller: true,
      seller: {
        name: 'All-Organics',
        logo: '/images/logo1.png',
        description: 'Best Seller for the betterment of the world!',
        rating: 4.5,
        numReviews: 120,
      },
    },
    {
      name: 'Alex',
      email: 'pkarbassi@hotmail.co.uk',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: false,
    },
  ],
  products: [
    //Number 1
    {
      name: 'Magners',
      category: 'Alchoholic Drinks',
      image: '/images/p1.jpg',
      price: 1.2,
      countInStock: 10,
      brand: 'Spain',
      rating: 4.5,
      numReviews: 10,
      description: 'High quality product',
      expDate: '2021-05-20',
    },
    {
      name: 'Apple',
      category: 'Fruits',
      image: '/images/p2.jpg',
      price: 1.0,
      countInStock: 15,
      brand: 'Spain',
      rating: 4.0,
      numReviews: 10,
      description: 'High quality product',
      expDate: '2021-06-20',
    },
    {
      name: 'Large Oranges',
      category: 'Fruits',
      image: '/images/p3.jpg',
      price: 1.0,
      countInStock: 0,
      brand: 'Spain',
      rating: 4.8,
      numReviews: 17,
      description: 'High quality product',
      expDate: '2021-06-20',
    },
    {
      name: 'Strawberries',
      category: 'Fruits',
      image: '/images/p4.jpg',
      price: 0.5,
      countInStock: 20,
      brand: 'Spain',
      rating: 4.5,
      numReviews: 14,
      description: 'High quality product',
      expDate: '2021-06-20',
    },
    //Number 5
    {
      name: 'Banana',
      category: 'Fruits',
      image: '/images/p5.jpg',
      price: 0.8,
      countInStock: 6,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'High quality product',
      expDate: '2021-06-20',
    },
    //Number 6
    {
      name: 'Canteloupe Melon',
      category: 'Fruits',
      image: '/images/p6.jpg',
      price: 5500,
      countInStock: 13,
      brand: 'Spain',
      rating: 4.5,
      numReviews: 15,
      description: 'High quality product',
      expDate: '2021-06-20',
    },
    //Number 7
    {
      name: 'Milk British Semi',
      category: 'Dairy',
      image: '/images/p7.jpg',
      price: 0.8,
      countInStock: 15,
      brand: 'Cravendale',
      rating: 4.5,
      numReviews: 10,
      description:
        'Pasteurised homogenised semi skimmed milk Supporting Our Dairy Farmers',
      expDate: '2021-06-20',
    },
    //Number 8
    {
      name: 'Coconut & Passion Fruit Cake',
      category: 'Cake',
      image: '/images/p8.jpg',
      price: 4.0,
      countInStock: 12,
      brand: 'Tase the Difference',
      rating: 4.5,
      numReviews: 10,
      description:
        'Coconut sponge layered with passion fruit jam, topped with passion fruit buttercream, decorated with passion fruit jam and toasted coconut. Topped with rich passion fruit buttercream With its generous filling of luscious passion fruit jam, this gorgeously moist coconut sponge is packed with tropical sunshine. Topped with rich passion fruit buttercream, it’s hand finished with a zigzag of jam and coconut shavings.',
      expDate: '2021-06-20',
    },
    // Number 9
    {
      name: 'The Best 4 Scotch Beef Quarter Pounders',
      category: 'Beef',
      image: '/images/p9.jpg',
      price: 3.0,
      countInStock: 11,
      brand: 'Morrisons',
      rating: 4.5,
      numReviews: 15,
      description: 'Gluten Free, Scotch Bee',
      expDate: '2022-03-22',
    },
    // Number 10
    {
      name: 'Hovis Wholemeal Bread 800g',
      category: 'Bread',
      image: '/images/p10.jpg',
      price: 3.0,
      countInStock: 11,
      brand: 'Morrisons',
      rating: 4.5,
      numReviews: 15,
      description: 'Medium Sliced Wholemeal Bread',
      expDate: '2022-03-22',
    },
    {
      name: 'Cabbage',
      category: 'Vegetables',
      image: '/images/p11.jpg',
      price: 2.0,
      countInStock: 5,
      brand: 'Spain',
      rating: 4.5,
      numReviews: 15,
      description: 'High quality product',
      expDate: '2022-03-22',
    },

    {
      name: 'Lettuce',
      category: 'Vegetables',
      image: '/images/p12.jpg',
      price: 2.5,
      countInStock: 25,
      brand: 'Portugal',
      rating: 4.0,
      numReviews: 3,
      description: 'High quality product',
      expDate: '2021-08-05',
    },
    {
      name: 'Tomato',
      category: 'Vegetables',
      image: '/images/p13.jpg',
      price: 1.5,
      countInStock: 45,
      brand: 'Spain',
      rating: 4.8,
      numReviews: 40,
      description: 'High quality product',
      expDate: '2021-07-15',
    },
    {
      name: 'Nectarine',
      category: 'Fruits',
      image: '/images/p14.jpg',
      price: 1.45,
      countInStock: 100,
      brand: 'Portugal',
      rating: 4.3,
      numReviews: 57,
      description: 'High quality product',
      expDate: '2021-12-09',
    },
    {
      name: 'Orange',
      category: 'Fruits',
      image: '/images/p15.jpg',
      price: 1.5,
      countInStock: 3,
      brand: 'Madagascar',
      rating: 5.0,
      numReviews: 12,
      description: 'High quality product',
      expDate: '2021-09-21',
    },
    // Number 16
    {
      name: 'Morrison Raspberries',
      category: 'Fruits',
      image: '/images/p16.jpg',
      price: 1.99,
      countInStock: 30,
      brand: 'Morrisons',
      rating: 3.0,
      numReviews: 2,
      description:
        'An 80g (2 handfuls) serving counts as 1 portion of your 5 a day fruit and vegetables. Aim to eat at least 5 portions of different fruit and vegetables each day. Remember that fresh, frozen, dried, canned and juice all count!',
      expDate: '2022-11-02',
    },
    {
      name: 'Broccoli',
      category: 'Vegetables',
      image: '/images/p17.jpg',
      price: 1.5,
      countInStock: 45,
      brand: 'Lithuania',
      rating: 1.0,
      numReviews: 8,
      description: 'High quality product',
      expDate: '2021-08-29',
    },
    {
      name: 'Pomegranate',
      category: 'Fruits',
      image: '/images/p18.jpg',
      price: 2.5,
      countInStock: 5,
      brand: 'France',
      rating: 4.5,
      numReviews: 30,
      description: 'High quality product',
      expDate: '2022-01-17',
    },
    {
      name: 'Cauliflower',
      category: 'Vegetables',
      image: '/images/p19.jpg',
      price: 2.5,
      countInStock: 3,
      brand: 'United Kingdom',
      rating: 3.5,
      numReviews: 17,
      description: 'High quality product',
      expDate: '2023-02-10',
    },
    {
      name: 'Lemon',
      category: 'Fruits',
      image: '/images/p20.jpg',
      price: 1.0,
      countInStock: 13,
      brand: 'Thailand',
      rating: 5.0,
      numReviews: 23,
      description: 'High quality product',
      expDate: '2021-03-27',
    },
    {
      name: 'Strawberry From Japan',
      category: 'Fruits',
      image: '/images/p21.jpg',
      price: 3.0,
      countInStock: 20,
      brand: 'Japan',
      rating: 5.0,
      numReviews: 33,
      description: 'High quality product',
      expDate: '2021-08-07',
    },
    {
      name: 'Fig',
      category: 'Fruits',
      image: '/images/p22.jpg',
      price: 2.0,
      countInStock: 13,
      brand: 'Madagascar',
      rating: 3.5,
      numReviews: 7,
      description: 'High quality product',
      expDate: '2022-11-12',
    },
    {
      name: 'Potato',
      category: 'Vegetables',
      image: '/images/p23.jpg',
      price: 2.0,
      countInStock: 95,
      brand: 'Romania',
      rating: 4.7,
      numReviews: 67,
      description: 'High quality product',
      expDate: '2021-10-09',
    },
    {
      name: 'Blueberry',
      category: 'Fruits',
      image: '/images/p24.jpg',
      price: 3.0,
      countInStock: 22,
      brand: 'France',
      rating: 4.3,
      numReviews: 10,
      description: 'High quality product',
      expDate: '2021-07-20',
    },
    {
      name: 'Bell Pepper',
      category: 'Vegetables',
      image: '/images/p25.jpg',
      price: 2.0,
      countInStock: 17,
      brand: 'Mexic',
      rating: 4.9,
      numReviews: 51,
      description: 'High quality product',
      expDate: '2021-10-10',
    },
    {
      name: 'Avocado',
      category: 'Vegetables',
      image: '/images/p26.jpg',
      price: 1.5,
      countInStock: 37,
      brand: 'United Kingdom',
      rating: 5.0,
      numReviews: 69,
      description: 'High quality product',
      expDate: '2022-07-05',
    },
    {
      name: 'Red Chilli Pepper',
      category: 'Vegetables',
      image: '/images/p27.jpg',
      price: 4.0,
      countInStock: 7,
      brand: 'United States',
      rating: 2.0,
      numReviews: 4,
      description: 'High quality product',
      expDate: '2021-06-29',
    },
    {
      name: 'Pumpkin',
      category: 'Vegetables',
      image: '/images/p28.jpg',
      price: 5.0,
      countInStock: 9,
      brand: 'Ireland',
      rating: 5.0,
      numReviews: 33,
      description: 'High quality product',
      expDate: '2021-06-20',
    },
    {
      name: 'Mango',
      category: 'Fruits',
      image: '/images/p29.jpg',
      price: 2.5,
      countInStock: 15,
      brand: 'Madagascar',
      rating: 3.3,
      numReviews: 9,
      description: 'High quality product',
      expDate: '2021-07-13',
    },
    {
      name: 'Passion Fruit',
      category: 'Fruits',
      image: '/images/p30.jpg',
      price: 7.0,
      countInStock: 3,
      brand: 'Japan',
      rating: 5.0,
      numReviews: 1,
      description: 'High quality product',
      expDate: '2021-08-01',
    },
  ],
};

export default data;
